### ISSUE TITLE
Typo in Grading Policy

### ISSUE THREAD

**Issue by SmithyGuySchool** [UIUC-ECE374B-SP23/UIUC-ECE374B-SP23.github.io#2]
In the grading policy tab, https://ecealgo.com/policies/grading , under the ICES form: 1% section, the second bullet point misspells the word "like" as "liek".
"I need feedback because I liek to iterate on the course every semester and try to make it better. This is a very different course than 2 years ago and I hope it’ll be different in 2 years time as well."

**Comment by NickvashKani** [comment]
I think I got it. Thanks!
