### ISSUE TITLE
Typo for homework section

### ISSUE THREAD

**Issue by AzrBlair** [UIUC-ECE374B-SP23/UIUC-ECE374B-SP23.github.io#4]
1. Under 4th tab of "_Couple things to note_", we have 2 typo for "homeowrks".
2. Also under 3ed tab of "_Homework Logistics: How to submit_", second sentence, there are two "are"s together.
3. Under 4th tab of "_Homework Grading Policies:_", the "I amm" with double m.

**Comment by NickvashKani** [comment]
I think I got them all. Thanks so much for your help!
